### ISSUE TITLE
Recent versions of matplotlib have removed the toolbar._active attribute

### ISSUE THREAD

**Issue by scizen9** [MickaelRigault/pyifu#2]
This crashes any interactive session that uses pyifu (extractstar.py --display, e.g.) and matplotlib version > 3.2.2

Three interactive functions use this private attribute and must be updated to use Axes.get_navigate_mode() function instead:

OLD (currently crashes in interactive mode):
if self.fig.canvas.manager.toolbar._active is not None:
    return

NEW (currently works):
for ax in self.fig.axes:
    if ax.get_navigate_mode() is not None:
        return
This may not be the most efficient way to use get_navigate_mode(), but it seems to work.

The functions in question are in pyifu/mplinteractive.py:

1. interact_onclick
2. interact_onrelease
3. interact_trackmotion

**Comment by MickaelRigault** [comment]
fixed it
